services:
  consumer: &consumer
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./src:/app/
    depends_on:
      - zookeeper
      - kafka

  producer:
    restart: on-failure
    <<: *consumer

  zookeeper:
    image: confluentinc/cp-zookeeper:${CP_VERSION:-7.5.2}
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:${CP_VERSION:-7.5.2}
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
